Repository PizzaCola-K/airbnb, pull requests merged in 2021-05, with the labels that each got.

#5 [FE] chore: :gear: Search 작업 중
  fe/public/image/destination/1.jpg
  fe/public/image/destination/2.jpg
  fe/public/image/destination/3.jpg
  fe/public/image/destination/4.jpg
  fe/public/image/heroimage.jpg
  fe/public/image/recommendation/1.jpg
  fe/public/image/recommendation/2.jpg
  fe/public/image/recommendation/3.jpg
  fe/public/image/recommendation/4.jpg
  fe/public/image/recommendation/5.jpg
  fe/public/image/recommendation/6.jpg
  fe/public/image/recommendation/7.jpg
  fe/public/image/recommendation/8.jpg
  fe/public/logo192.png
  fe/public/logo512.png
  fe/src/component/header/Header.tsx
  fe/src/component/header/gnb/LoginButton.tsx
  fe/src/component/header/gnb/Logo.tsx
  fe/src/component/header/gnb/Navigation.tsx
  fe/src/component/header/search-bar/Personnel.tsx
  fe/src/component/header/search-bar/SearchBar.tsx
  fe/src/component/header/search-bar/SearchButton.tsx
  fe/src/component/header/search-bar/SearchDate.tsx
  fe/src/component/header/search-bar/SearchPersonnel.tsx
  fe/src/component/header/search-bar/SearchPrice.tsx
  fe/src/component/main/Destination.tsx
  fe/src/component/main/Footer.tsx
  fe/src/component/main/Main.tsx
  fe/src/component/main/Recommendation.tsx
  fe/src/component/ui-util/Calendar.tsx
  fe/src/component/ui-util/LabelInput.tsx
  fe/src/component/ui-util/Modal.tsx
  fe/src/component/ui-util/RangeSlider.tsx
Labels: FE, Feat

#7 [FE] Make Modal
  fe/src/component/modal/modal.jsx
  fe/src/component/modal/modalContent/ModalContent.jsx
  fe/src/component/modal/modalContent/information/Info.jsx
  fe/src/component/modal/modalContent/sum/Sum.jsx
Labels: FE, Feat

#18 [FE] SearchBar PopUp 생성
  fe/src/component/header/search-bar/SearchBar.tsx
  fe/src/component/header/search-bar/SearchDate.tsx
  fe/src/component/header/search-bar/SearchPersonnel.tsx
  fe/src/component/header/search-bar/SearchPrice.tsx
  fe/src/component/header/search-bar/popUp/PopUp.tsx
Labels: FE

#19 [BE] Place, Reservation 설계
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/codesquad/team17/gnb/GnbApplication.java
  BE/src/main/java/codesquad/team17/gnb/exception/NotFoundException.java
  BE/src/main/java/codesquad/team17/gnb/place/controller/PlaceController.java
  BE/src/main/java/codesquad/team17/gnb/place/domain/JdbcPlaceRepository.java
  BE/src/main/java/codesquad/team17/gnb/place/domain/Location.java
  BE/src/main/java/codesquad/team17/gnb/place/domain/Option.java
  BE/src/main/java/codesquad/team17/gnb/place/domain/Place.java
  BE/src/main/java/codesquad/team17/gnb/place/domain/PlaceRepository.java
  BE/src/main/java/codesquad/team17/gnb/place/domain/PlaceSql.groovy
  BE/src/main/java/codesquad/team17/gnb/place/dto/LocationDto.java
  BE/src/main/java/codesquad/team17/gnb/place/dto/OptionDto.java
  BE/src/main/java/codesquad/team17/gnb/place/dto/PlaceSummary.java
  BE/src/main/java/codesquad/team17/gnb/place/service/PlaceService.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/schema.sql
  BE/src/test/java/codesquad/team17/gnb/GnbApplicationTests.java
  BE/src/test/java/codesquad/team17/gnb/place/domain/PlaceRepositoryTest.java
  BE/src/test/resources/data.sql
Labels: BE, Feat

#20 [FE] 팝업 onClick Event 생성
  fe/package-lock.json
  fe/src/App.tsx
  fe/src/component/header/search-bar/SearchBar.tsx
  fe/src/component/header/search-bar/SearchDate.tsx
  fe/src/component/header/search-bar/SearchPersonnel.tsx
  fe/src/component/header/search-bar/popUp/PopUp.tsx
  fe/src/component/ui-util/LabelInput.tsx
Labels: FE

#22 [FE} 헤더 이벤트 구현
  fe/src/App.tsx
  fe/src/component/header/Header.tsx
  fe/src/component/header/gnb/LoginButton.tsx
  fe/src/component/header/search-bar/SearchBar.tsx
  fe/src/component/header/search-bar/SearchDate.tsx
  fe/src/component/header/search-bar/SearchPersonnel.tsx
  fe/src/component/header/search-bar/SearchPrice.tsx
  fe/src/component/list/List.tsx
  fe/src/component/list/Stay.tsx
  fe/src/component/modal/modal.jsx
  fe/src/component/modal/modal.tsx
  fe/src/component/modal/modalContent/ModalContent.jsx
  fe/src/util.ts
Labels: FE, Feat

#24 [BE] 검색 기능
  BE/src/main/java/codesquad/team17/gnb/GnbApplication.java
  BE/src/main/java/codesquad/team17/gnb/place/controller/PlaceController.java
  BE/src/main/java/codesquad/team17/gnb/place/domain/JdbcPlaceRepository.java
  BE/src/main/java/codesquad/team17/gnb/place/domain/Place.java
  BE/src/main/java/codesquad/team17/gnb/place/domain/PlaceRepository.java
  BE/src/main/java/codesquad/team17/gnb/place/domain/PlaceSql.groovy
  BE/src/main/java/codesquad/team17/gnb/place/dto/PlaceQueries.java
  BE/src/main/java/codesquad/team17/gnb/place/service/PlaceService.java
  BE/src/test/java/codesquad/team17/gnb/place/domain/PlaceRepositoryTest.java
Labels: BE

#25 [FE] popup 수정
  fe/src/component/header/search-bar/SearchBar.tsx
  fe/src/component/ui-util/LabelInput.tsx
Labels: FE

#26 [FE] chore: :wrench: 작업 중
  fe/package-lock.json
  fe/package.json
  fe/src/component/header/search-bar/popUp/PopUp.tsx
  fe/src/component/header/search-bar/popUp/personnel/Personnel.tsx
  fe/src/component/header/search-bar/popUp/personnel/standard/Standard.tsx
  fe/src/component/ui-util/Calendar.tsx
  fe/src/component/ui-util/Month.tsx
Labels: FE, Feat

#29 [BE] 인증 (FE)
  BE/build.gradle
  BE/src/main/java/codesquad/team17/gnb/auth/controller/AuthController.java
  BE/src/main/java/codesquad/team17/gnb/auth/dto/AccessTokenRequest.java
  BE/src/main/java/codesquad/team17/gnb/auth/dto/AccessTokenResponse.java
  BE/src/main/java/codesquad/team17/gnb/auth/dto/AuthJwt.java
  BE/src/main/java/codesquad/team17/gnb/auth/dto/GithubUser.java
  BE/src/main/java/codesquad/team17/gnb/auth/service/AuthService.java
  BE/src/main/java/codesquad/team17/gnb/auth/service/JwtUtils.java
  BE/src/main/java/codesquad/team17/gnb/config/WebConfig.java
  BE/src/main/java/codesquad/team17/gnb/user/domain/User.java
  BE/src/main/java/codesquad/team17/gnb/user/repository/JdbcUserRepository.java
  BE/src/main/java/codesquad/team17/gnb/user/repository/UserRepository.java
  BE/src/main/java/codesquad/team17/gnb/user/repository/UserSql.groovy
  BE/src/main/resources/application-auth.properties
  BE/src/main/resources/application.properties
  BE/src/main/resources/schema.sql
  BE/src/test/java/codesquad/team17/gnb/user/repository/UserRepositoryTest.java
Labels: BE, Feat
